### ISSUE TITLE
Club de Ajedrez

### ISSUE THREAD

**Issue by luxiano** [eikiu/rg-actividades#1]
"Brindamos clases de ajedrez en nuestra sede los dias Martes y Jueves de 19hs a 20hs. En Maria Auxiliadora Nº 661, Patio Interno, Chacra II, Rio Grande, Tierra del Fuego."

La última vez que pasé, seguía ahí. Acá está la página: http://clubdeajedrezderiogrande.blogspot.com.ar (no se actualiza desde el 2013).

PD: no, no quería hacer el lío de forkear. :P

**Comment by aquinzi** [comment]
Gracias!. Si queres que te anote como colaborador, avisame con qué nombre te pongo (:P) y, opcional, algo de contacto (como web, perfil de red social, o similar)

**Comment by luxiano** [comment]
No te hagas drama ;)
