### ISSUE TITLE
Varias actividades para ancianos

### ISSUE THREAD

**Issue by luxiano** [eikiu/rg-actividades#2]
Acá http://dsocial.tierradelfuego.gov.ar/index.php/direccion-de-inclusion-social tenés lo que supuestamente (uno nunca sabe) dan en el Hogar de Día (Muñoz 927).

**Comment by aquinzi** [comment]
Gracias!. Si queres que te anote como colaborador, avisame con qué nombre te pongo (:P) y, opcional, algo de contacto (como web, perfil de red social, o similar)

**Comment by luxiano** [comment]
No te hagas drama ;)
